/**
 * Mock temporário do dossiê de produto, usado pela rota /arquivo/[slug]
 * enquanto não existe /content/products/*.json validado com Zod
 * (BRIEF.md, seção 10).
 */
import type { ProductDetail } from "@/types/product";

const CONFERENCIA_PADRAO = [
  "Etiqueta original conferida",
  "Numeração de série verificada",
  "Costura e acabamento inspecionados",
  "Caixa original íntegra",
  "Acessórios completos",
];

const GALLERY_PADRAO = ["Estúdio", "Unidade recebida", "Detalhe", "Caixa"];

export const MOCK_PRODUCT_DETAILS: ProductDetail[] = [
  {
    id: "1",
    slug: "air-jordan-1-tokyo",
    brand: "Nike",
    name: "Air Jordan 1 Retro High OG",
    referencia: "NSE-0142",
    priceCents: 189000,
    rarity: "raro",
    images: { primary: "" },
    origin: "Tóquio",
    stockAvailable: 1,
    stockTotal: 2,
    sizes: [
      { label: "38", available: false },
      { label: "39", available: true },
      { label: "40", available: true },
      { label: "41", available: true },
      { label: "42", available: false },
      { label: "43", available: true },
    ],
    provenance: {
      filial: "Nike Tokyo Flagship",
      pais: "Japão",
      dataAquisicao: "03/10/2026",
      condicao: "Deadstock",
    },
    conferencia: CONFERENCIA_PADRAO,
    galleryLabels: GALLERY_PADRAO,
    relatedSlugs: ["bape-shark-hoodie", "kith-quilted-vest"],
  },
  {
    id: "2",
    slug: "supreme-box-logo",
    brand: "Supreme",
    name: "Box Logo Hoodie",
    referencia: "NSE-0098",
    priceCents: 420000,
    rarity: "peca-unica",
    images: { primary: "" },
    origin: "Nova York",
    stockAvailable: 1,
    stockTotal: 1,
    sizes: [
      { label: "P", available: false },
      { label: "M", available: false },
      { label: "G", available: true },
      { label: "GG", available: false },
    ],
    provenance: {
      filial: "Supreme New York",
      pais: "Estados Unidos",
      dataAquisicao: "22/09/2026",
      condicao: "Novo lacrado",
    },
    conferencia: CONFERENCIA_PADRAO,
    galleryLabels: GALLERY_PADRAO,
    relatedSlugs: ["kith-quilted-vest", "palace-tri-ferg-jacket"],
  },
  {
    id: "3",
    slug: "bape-shark-hoodie",
    brand: "BAPE",
    name: "Shark Full Zip Hoodie",
    referencia: "NSE-0075",
    priceCents: 265000,
    rarity: "limitado",
    images: { primary: "" },
    origin: "Osaka",
    stockAvailable: 3,
    stockTotal: 5,
    sizes: [
      { label: "P", available: true },
      { label: "M", available: true },
      { label: "G", available: true },
      { label: "GG", available: false },
    ],
    provenance: {
      filial: "BAPE Osaka",
      pais: "Japão",
      dataAquisicao: "18/09/2026",
      condicao: "Novo lacrado",
    },
    conferencia: CONFERENCIA_PADRAO,
    galleryLabels: GALLERY_PADRAO,
    relatedSlugs: ["air-jordan-1-tokyo", "stone-island-shadow-jacket"],
  },
  {
    id: "4",
    slug: "stone-island-shadow-jacket",
    brand: "Stone Island",
    name: "Shadow Project Jacket",
    referencia: "NSE-0061",
    priceCents: 385000,
    rarity: "raro",
    images: { primary: "" },
    origin: "Milão",
    stockAvailable: 1,
    stockTotal: 3,
    sizes: [
      { label: "M", available: true },
      { label: "G", available: false },
      { label: "GG", available: true },
    ],
    provenance: {
      filial: "Stone Island Milano",
      pais: "Itália",
      dataAquisicao: "29/09/2026",
      condicao: "Deadstock",
    },
    conferencia: CONFERENCIA_PADRAO,
    galleryLabels: GALLERY_PADRAO,
    relatedSlugs: ["bape-shark-hoodie", "palace-tri-ferg-jacket"],
  },
  {
    id: "5",
    slug: "kith-quilted-vest",
    brand: "Kith",
    name: "Quilted Vest",
    referencia: "NSE-0113",
    priceCents: 148000,
    rarity: "comum",
    images: { primary: "" },
    origin: "Nova York",
    stockAvailable: 4,
    stockTotal: 6,
    sizes: [
      { label: "P", available: true },
      { label: "M", available: true },
      { label: "G", available: true },
      { label: "GG", available: true },
    ],
    provenance: {
      filial: "Kith Manhattan",
      pais: "Estados Unidos",
      dataAquisicao: "05/10/2026",
      condicao: "Novo lacrado",
    },
    conferencia: CONFERENCIA_PADRAO,
    galleryLabels: GALLERY_PADRAO,
    relatedSlugs: ["air-jordan-1-tokyo", "supreme-box-logo"],
  },
  {
    id: "6",
    slug: "palace-tri-ferg-jacket",
    brand: "Palace",
    name: "Tri-Ferg Track Jacket",
    referencia: "NSE-0129",
    priceCents: 176000,
    rarity: "limitado",
    images: { primary: "" },
    origin: "Londres",
    stockAvailable: 2,
    stockTotal: 4,
    sizes: [
      { label: "P", available: true },
      { label: "M", available: false },
      { label: "G", available: true },
      { label: "GG", available: true },
    ],
    provenance: {
      filial: "Palace Soho London",
      pais: "Reino Unido",
      dataAquisicao: "27/09/2026",
      condicao: "Deadstock",
    },
    conferencia: CONFERENCIA_PADRAO,
    galleryLabels: GALLERY_PADRAO,
    relatedSlugs: ["supreme-box-logo", "stone-island-shadow-jacket"],
  },
];

export function getProductDetailBySlug(slug: string): ProductDetail | undefined {
  return MOCK_PRODUCT_DETAILS.find((product) => product.slug === slug);
}
