/**
 * Mock temporário de produtos, usado por /estilo e pela Home enquanto não
 * existe /content/products/*.json validado com Zod (BRIEF.md, seção 10).
 */
import type { ProductSummary } from "@/types/product";

export const MOCK_PRODUCTS: ProductSummary[] = [
  {
    id: "1",
    slug: "air-jordan-1-tokyo",
    brand: "Nike",
    name: "Air Jordan 1 Retro High OG",
    referencia: "NSE-0142",
    priceCents: 189000,
    rarity: "raro",
    images: { primary: "" },
    origin: "Tóquio",
    stockAvailable: 1,
    stockTotal: 2,
  },
  {
    id: "2",
    slug: "supreme-box-logo",
    brand: "Supreme",
    name: "Box Logo Hoodie",
    referencia: "NSE-0098",
    priceCents: 420000,
    rarity: "peca-unica",
    images: { primary: "" },
    origin: "Nova York",
    stockAvailable: 1,
    stockTotal: 1,
  },
  {
    id: "3",
    slug: "bape-shark-hoodie",
    brand: "BAPE",
    name: "Shark Full Zip Hoodie",
    referencia: "NSE-0075",
    priceCents: 265000,
    rarity: "limitado",
    images: { primary: "" },
    origin: "Osaka",
    stockAvailable: 3,
    stockTotal: 5,
  },
  {
    id: "4",
    slug: "stone-island-shadow-jacket",
    brand: "Stone Island",
    name: "Shadow Project Jacket",
    referencia: "NSE-0061",
    priceCents: 385000,
    rarity: "raro",
    images: { primary: "" },
    origin: "Milão",
    stockAvailable: 1,
    stockTotal: 3,
  },
  {
    id: "5",
    slug: "kith-quilted-vest",
    brand: "Kith",
    name: "Quilted Vest",
    referencia: "NSE-0113",
    priceCents: 148000,
    rarity: "comum",
    images: { primary: "" },
    origin: "Nova York",
    stockAvailable: 4,
    stockTotal: 6,
  },
  {
    id: "6",
    slug: "palace-tri-ferg-jacket",
    brand: "Palace",
    name: "Tri-Ferg Track Jacket",
    referencia: "NSE-0129",
    priceCents: 176000,
    rarity: "limitado",
    images: { primary: "" },
    origin: "Londres",
    stockAvailable: 2,
    stockTotal: 4,
  },
];
